import { Race } from "@/types";

export const racesData: Race[] = [
  {
    raceId: 1,
    year: 1954,
    round: 8,
    circuitId: 1,
    name: "Albert Park Grand Prix Circuit",
    date: "1954-09-05",
    time: "\\N",
    url: "http://en.wikipedia.org/wiki/1954_Italian_Grand_Prix",
    fp1_date: "\\N",
    fp1_time: "\\N",
    fp2_date: "\\N",
    fp2_time: "\\N",
    fp3_date: "\\N",
    fp3_time: "\\N",
    quali_date: "\\N",
    quali_time: "\\N",
    sprint_date: "\\N",
    sprint_time: "\\N",
  },
  {
    raceId: 2,
    year: 1954,
    round: 8,
    circuitId: 1,
    name: "Albert Park Grand Prix Circuit",
    date: "1954-09-05",
    time: "\\N",
    url: "http://en.wikipedia.org/wiki/1954_Italian_Grand_Prix",
    fp1_date: "\\N",
    fp1_time: "\\N",
    fp2_date: "\\N",
    fp2_time: "\\N",
    fp3_date: "\\N",
    fp3_time: "\\N",
    quali_date: "\\N",
    quali_time: "\\N",
    sprint_date: "\\N",
    sprint_time: "\\N",
  },
];
